### ISSUE TITLE
Adopt `@endo` packages

### ISSUE THREAD

**Issue by mhofman** [Agoric/testnet-load-generator#100]
Packages like `eventual-send` have moved onto Endo, which means `agoric install` no longer links them from the `agoric-sdk` repo and we end up pulling old versions from npm. These packages should be stable and backwards compatible enough that using their new `@endo` version should work. Probably should double check running the loadgen on old agoric-sdk revisions.

**Comment by mhofman** [comment]
In particular, using an outdated version allowed a deprecated and now forbidden usage of `E()`. See https://github.com/Agoric/testnet-load-generator/pull/85#discussion_r1085615146

**Comment by erights** [comment]
Could `agoric-install` take into account what versions of @endo packages agoric-sdk depends on? I always assumed that it did so. I'm surprised that not doing so has not caused more trouble.

**Comment by mhofman** [comment]
Because of identity discontinuity? That's a question for `agoric-sdk`, but if I had to guess, I'd say no since you can only `yarn link` what is in your own repo.

**Comment by erights** [comment]
Wow. In that case, I don't see how `agoric install` can ever be correct --- can ever bring about a configurations in which each package's dependencies are properly satisfied. Am I missing something?

If this cannot be fixed, I'm gonna suggest again the repeatedly-rejected option: We should merge the two monorepos into one big one.

**Comment by mhofman** [comment]
Nope, we should start moving to NPM installed packages for dapps (which this technically is), and not rely on `yarn link` for most cases.

**Comment by erights** [comment]
So what does that suggest for how to fix `agoric install` now?
