### ISSUE TITLE
CI uses Node 12, but agoric-sdk requires Node >=14.15.0

### ISSUE THREAD

**Issue by katelynsills** [Agoric/testnet-load-generator#11]
![Screen Shot 2021-07-22 at 11 41 24 AM](https://user-images.githubusercontent.com/2441069/126691933-87c53764-fcfc-419a-a8a8-6853ee435fd5.png)

**Comment by mhofman** [comment]
Closed by https://github.com/Agoric/testnet-load-generator/pull/13
