### ISSUE TITLE
add remote-control feature

### ISSUE THREAD

**Issue by warner** [Agoric/testnet-load-generator#14]
For the next testnet phase, we plan to recruit all validator operators to run load-generator nodes. They'll be asked to point the loadgen at their own (local) RPC server, which will hopefully fix some of the problems we've had with RPC servers falling over.

To manage this, we want to add a central coordinator. Each generator will be run with a coordinator URL and a nickname (their validator moniker) as `argv` arguments. The generator will establish a WebSocket connection to this URL and register itself for updates (instead of / in addition to the local URL listener). We'll run the server, and when we want to crank up the load, the server will tell some subset of validators to run faster.

We should include status updates on this websocket channel: each time a load operation completes, so we can measure the overall offered/accepted load.

The coordination server can live in this repository. The control port should have a simple API token to protect access. We won't bother applying any protection to the client connections.

**Comment by mhofman** [comment]
My current thinking is to leverage a Firebase Real-time DB to handle the communication with the loadgen: the coordinator would update the current loadgen config for each validator (possibly with some level of indirection to avoid having to update dozens of entries at every loadgen change), and each validator would append its loadgen activity to a dedicated collection. If we want any authentication, a signed JWT containing the moniker, with simple security rules enforcing writing activity in a path containing the moniker.
