### ISSUE TITLE
add AMM task

### ISSUE THREAD

**Issue by warner** [Agoric/testnet-load-generator#3]
The job is to add `loadgen/task-amm.js` to define the setup and cycle of a task that exercises the AMM contract.

The setup phase should

* install and instantiate a contract which implements a pair of Issuers and an AMM
* mint some tokens of each type, in a pair of holding purses
* record the objects in the "scratch" table for later use

The cycle function should:

* fetch the objects from the scratch table (which does not require a chain operation)
* decide whether we should sell A for B, or sell B for A
  * overall we should alternate between these two operations
  * the state which helps us remember this should be somewhat durable
    * we can do a one-time prepare function which queries the balances of both purses, and chooses an initial direction which moves us towards parity
    * then for as long as the loadgen program runs, it can just alternate
    * if the loadgen program is killed, the next time we should move towards parity instead of away from it
    * as long as we have enough tokens to handle a couple of swings, we should never run out
* create an offer to sell one for the other, deliver it, fetch the two resulting balances and display them

This task won't use the wallet at all, so it may induce somewhat less load than a real user operation. A later task will be to perform a more complete simulation of the wallet approval process.

**Comment by dckc** [comment]
I'm pretty sure this is expected for the staking dynamics phase.

**Comment by warner** [comment]
I just landed this, thanks @katelynsills for the help! We decided to make the AMM task perform both trades in each cycle, rather than alternating.
