### ISSUE TITLE
move load generators into ag-solo (spawner) vat

### ISSUE THREAD

**Issue by warner** [Agoric/testnet-load-generator#6]
agoric-sdk finally has GC support in the kernel and in comms. But the "captp" library does not yet participate in GC, so any objects that traverse a captp link will not get released (I think.. I must admit I don't understand our "captp" library very well).

The load-generation tasks defined in this repository (e.g. `loadgen/task-trade-amm.js`) all run in a deploy script, which is connected to the `ag-solo` swingset via captp. As a result, all of the Payments, Seats, and Invitations used by the load generation process cause the corresponding chain-side Remotables to be pinned in memory for the lifetime of the solo node (and, since our comms layer doesn't have a way to delete remotes, they're also pinned for the lifetime of the chain).

We can improve this by moving the load generation tools into a real vat. Basically each task needs to be rewritten as either a complete dynamic vat, or as a piece of code to be evaluated within some real vat. I know the solo's "spawner" does one of these two modes (probably the latter).

The deploy script should install the generator code into the ag-solo spawner service. Then the deploy script should send the generator a message to initiate a cycle, and get back a response when the cycle is complete. This "initiate" message won't contain any object references (no Seats or Payments), so captp won't be holding onto a reference to those things, so they should be successfully garbage collected.

This will let us 1: exercise comms GC and 2: reduce the memory footprint of the chain (since the Remotables should get released).

One downside is that it won't be a realistic representation of the work done by e.g. user Wallet frontends, because all the Payments received by those are also going to be pinned by captp. We absolutely need to fix those somehow, maybe by one f more of:
* teach captp to participate in GC
* make the wallet be a real vat
* teach captp to notice when the remote is gone and drop its references and then drop the remote on a regular basis
* *something* to make sure all object references live inside environments sophisticated enough to drop them in a timely fashion

But for now I think we really need a way to generate chain-side load without also accumulating garbage forever.

**Comment by mhofman** [comment]
> We can improve this by moving the load generation tools into a real vat

> One downside is that it won't be a realistic representation of the work done by e.g. user Wallet frontends

I thought we wanted the data captured by the load generator to be somewhat representative of real world usage of the chain. I'm worried that by not actioning the ag-solo chain link we wouldn't be able to measure how long restarts would actually take in the real world, or the impact of a change in a path that is no longer exercised.

Since we control the load generator, would it make sense to restart it multiple time during each phase and force a GC somehow to keep the test representative but limit the impact from the known lack of GC support in captp? (I guess bullet 3 above)

**Comment by warner** [comment]
Hm, good questions. I guess there's a tradeoff between different things we might measure at different stages.

For now, I care the most about whether GC has bugs, if GC actually manages to save space, if that saved space means that vats run faster (especially during restart), and what the ram/disk/cpu consumption curves look like in the ideal case where we have measurable traffic and all our space-saving tools are working.

If the wallet code isn't participating in GC, that's a bug that's going to cause performance problems, but I don't want that to prevent us from measuring the performance of the other parts of the system.

It might be useful to run two parallel perf tests, one with the loadgen running in an ag-solo spawner environment (to tell us about GC behavior), and a separate one with loadgen running in a deploy script (to tell us that captp doesn't do GC). An even more realistic one will be to have loadgen talk to the wallet code, which will tell us that the wallet uses captp *and* that captp doesn't do GC, as well as exercising the wallet code (super important, GUI CI is always tricky). But the last two won't tell us anything we don't already know for this week, so they aren't my priority right now.

> I'm worried that by not actioning the ag-solo chain link

To be precise, we're exercising the chain-solo link equally heavily in both "loadgen lives in deploy script" and "loadgen lives in ag-solo spawner". In fact we'll probably be sending *more* messages in the ag-solo-spawner case, because it'll be emitting and receiving GC messages. What we're not exercising as heavily is the deployscript-solo link (the captp one that runs over websockets).
